# Generated by Django 3.0.5 on 2020-04-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.CharField(default='bg_1.jpg', max_length=50)),
                ('description', models.TextField(default='Slider item description')),
                ('header', models.TextField(default='Slider item header')),
            ],
        ),
    ]
