# Generated by Django 3.0.5 on 2020-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0002_slideritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='column_left_color',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='column_mid_color',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='column_right_color',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='footer_left',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='navbar_title',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='site_title',
        ),
        migrations.AddField(
            model_name='meta',
            name='attribute_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='meta',
            name='value',
            field=models.TextField(default=''),
        ),
    ]
