# Generated by Django 3.0.5 on 2020-04-14 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('httpsrv', '0003_auto_20200414_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('content', models.TextField(default='')),
                ('title', models.CharField(default='', max_length=50)),
                ('tags', models.CharField(default='', max_length=65)),
                ('image', models.CharField(default='bg_1.jpg', max_length=65)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
