# Generated by Django 3.0.5 on 2020-04-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0004_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='datetime',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='day',
            field=models.CharField(default='01', max_length=25),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='month',
            field=models.CharField(default='January', max_length=25),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='preview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='year',
            field=models.CharField(default='2020', max_length=25),
        ),
    ]
